"""add organizer field to events model

Revision ID: cc33e8d5f4a4
Revises: f960459f3067
Create Date: 2019-04-15 13:47:46.440283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc33e8d5f4a4'
down_revision = 'f960459f3067'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('organizer', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'organizer')
    # ### end Alembic commands ###
